Repository Microsoft-community/Dotsimus, pull requests merged in 2021-08, with the labels that each got.

#97 Fix typo
  README.md
Labels: bug

#95 V13 refactoring
  package.json
  src/features/commands/reportApprovalAction.js
  src/features/commands/reportRejectionAction.js
  src/features/commands/rules.js
  src/features/commands/server.js
  src/features/commands/toxicityEval.js
  src/features/commands/user.js
  src/index.js
Labels: enhancement

#103 V13 fixes and improvements
  package.json
  src/features/commands/about.js
  src/features/commands/buttons/reportApprovalAction.js
  src/features/commands/buttons/reportRejectionAction.js
  src/features/commands/flip.js
  src/features/commands/help.js
  src/features/commands/rules.js
  src/features/commands/server.js
  src/features/commands/toxic.js
  src/features/commands/user.js
  src/index.js
Labels: bug, enhancement

#105 Initial analytics implementation
  .gitignore
  events.json
  src/features/commands/about.js
  src/features/commands/rules.js
  src/index.js
  src/utils.js
Labels: enhancement

#111 Remove extra space before the word "Insult" in "/toxic" command embed
  src/features/commands/toxic.js
Labels: bug

#110 Send /toxic message as ephermal if it goes above threshold
  src/features/commands/about.js
  src/features/commands/buttons/hideToxicityEmbed.js
  src/features/commands/buttons/reportApprovalAction.js
  src/features/commands/buttons/reportRejectionAction.js
  src/features/commands/buttons/sendToxicityEmbed.js
  src/features/commands/flip.js
  src/features/commands/rules.js
  src/features/commands/server.js
  src/features/commands/toxic.js
  src/features/commands/user.js
  src/index.js
Labels: enhancement
